matrix:
  - name: Markdown
    aspell:
      lang: en_US
    pipeline:
      - pyspelling.filters.markdown
    sources:
      - '**/*.md'
    default_encoding: utf-8
    dictionary:
      wordlists: [.wordlist.txt]
