name: Build site and deploy to Pages

on:
  push:
    branches: [main]

permissions:
  # allow bot to create or push to gh-pages
  contents: write 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout source files and theme
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # install hugo
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.1'
          extended: true
      # build site
      - name: build
        run: hugo --minify --baseURL "https://nandstand.github.io/hugo-sandbox/"
      # deploy to gh-pages
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
