name: deploy

on:
  push:
    branches: [main]

permissions:
  # allow bot to create / push to gh-pages
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          # don't forget theme submodule
          submodules: recursive 
      - uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: '0.147.1' 
          extended: true
      - name: generate site 
        run: hugo --minify 
      - name: upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          retention-days: 1 

  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: checkout site source
        uses: actions/checkout@v4
      - name: run markdown linter
        uses: DavidAnson/markdownlint-cli2-action@v19.1.0
        with:
          globs: '**/*.md'
          config: .markdownlint.yaml

  html-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download site build
        uses: actions/download-artifact@v4
        with: 
          name: site 
          path: ./public
      - name: html test (link checks, img alt tags)
        uses: wjdp/htmltest-action@v0.13.0-rc1
        with: 
          config: .htmltest.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download site build
        uses: actions/download-artifact@v4
        with: 
          name: site 
          path: ./public
      - name: deploy site to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
